services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: apiconf-agent-backend
    env_file:
      - .env
    networks:
      - apiconf-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/agents/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./data:/app/data

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: apiconf-agent-nginx
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - apiconf-network
    restart: unless-stopped

networks:
  apiconf-network:
    driver: bridge 